name: CI

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "lib/**"
      - "*.gemspec"
      - "spec/**"
      - "Rakefile"
      - "Gemfile"
  pull_request:
    branches:
      - master
  create:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.1"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run RSpec code examples
        run: bundle exec rake spec
